const API_BASE_URL = "http://127.0.0.1:8000";

const fileInput = document.getElementById("fileInput");
const uploadBtn = document.getElementById("uploadBtn");
const askBtn = document.getElementById("askBtn");
const uploadStatus = document.getElementById("uploadStatus");
const selectedFileElement = document.getElementById("selectedFile");
const activeDocumentElement = document.getElementById("activeDocument");
const uploadHintElement = document.getElementById("uploadHint");
const questionInput = document.getElementById("question");
const answerElement = document.getElementById("answer");
const sourcesElement = document.getElementById("sources");

uploadBtn.addEventListener("click", uploadPDF);
askBtn.addEventListener("click", askQuestion);
fileInput.addEventListener("change", updateSelectedFile);

let documentReady = false;
let activeDocumentName = "";
let pendingUpload = false;

function updateSelectedFile() {
    const file = fileInput.files[0];
    if (file) {
        selectedFileElement.textContent = `Selected file: ${file.name}`;
        pendingUpload = true;
        uploadHintElement.textContent = "File selected. Click Upload and Index before asking questions with this PDF.";
    } else {
        selectedFileElement.textContent = "No file selected.";
        pendingUpload = false;
        uploadHintElement.textContent = "Choose a PDF, then click Upload and Index to use it for RAG.";
    }
}

async function uploadPDF() {
    const file = fileInput.files[0];

    if (!file) {
        uploadStatus.textContent = "Choose a PDF file first.";
        return;
    }

    const formData = new FormData();
    formData.append("file", file);

    documentReady = false;
    activeDocumentName = "";
    uploadBtn.disabled = true;
    uploadStatus.textContent = "Uploading and indexing your PDF. The first upload can take a little longer while models load.";
    activeDocumentElement.textContent = "Indexing document...";
    uploadHintElement.textContent = "Please wait while the document is being indexed.";
    answerElement.textContent = "Your answer will appear here.";
    sourcesElement.innerHTML = '<p class="muted">No sources retrieved yet.</p>';

    try {
        const response = await fetch(`${API_BASE_URL}/upload`, {
            method: "POST",
            body: formData
        });

        const data = await response.json().catch(() => ({}));
        if (!response.ok) {
            throw new Error(data.detail || "Upload failed.");
        }

        const documentInfo = data.document;
        documentReady = true;
        activeDocumentName = documentInfo.filename;
        pendingUpload = false;
        selectedFileElement.textContent = `Uploaded file: ${file.name}`;
        activeDocumentElement.textContent = `Indexed document: ${documentInfo.filename}`;
        uploadStatus.textContent = `${documentInfo.filename} indexed with ${documentInfo.chunks_created} chunks across ${documentInfo.pages_indexed} pages.`;
        uploadHintElement.textContent = "This indexed PDF will now be used for RAG answers.";
    } catch (error) {
        uploadStatus.textContent = formatErrorMessage(error, "Upload failed.");
        activeDocumentElement.textContent = "No document is indexed yet.";
        uploadHintElement.textContent = "Choose a PDF, then click Upload and Index to use it for RAG.";
    } finally {
        uploadBtn.disabled = false;
    }
}

async function askQuestion() {
    const query = questionInput.value.trim();
    if (!query) {
        answerElement.textContent = "Enter a question first.";
        return;
    }
    if (pendingUpload) {
        answerElement.textContent = "A PDF is selected but not indexed yet. Click Upload and Index first.";
        sourcesElement.innerHTML = '<p class="muted">The selected PDF has not been indexed yet.</p>';
        return;
    }

    askBtn.disabled = true;
    answerElement.textContent = "Generating answer...";
    sourcesElement.innerHTML = documentReady
        ? `<p class="muted">Searching ${activeDocumentName}...</p>`
        : '<p class="muted">No PDF indexed, so the response will come directly from the LLM.</p>';

    try {
        const response = await fetch(`${API_BASE_URL}/ask`, {
            method: "POST",
            headers: {
                "Content-Type": "application/json"
            },
            body: JSON.stringify({
                query,
                top_k: 3
            })
        });

        const data = await response.json().catch(() => ({}));
        if (!response.ok) {
            throw new Error(data.detail || "Failed to generate an answer.");
        }

        answerElement.textContent = data.answer;
        renderSources(data.sources || []);
        if (data.mode === "llm") {
            activeDocumentElement.textContent = "No PDF indexed. Answer generated by the LLM only.";
        } else if (data.document) {
            activeDocumentElement.textContent = `Indexed document: ${data.document}`;
        }
    } catch (error) {
        answerElement.textContent = formatErrorMessage(error, "Failed to generate an answer.");
        sourcesElement.innerHTML = '<p class="muted">No sources available.</p>';
    } finally {
        askBtn.disabled = false;
    }
}

function renderSources(sources) {
    if (!sources.length) {
        sourcesElement.innerHTML = '<p class="muted">No document context was used for this answer.</p>';
        return;
    }

    sourcesElement.innerHTML = sources
        .map(
            (source) => `
                <article class="source-item">
                    <p class="source-title">${source.source} - page ${source.page}</p>
                    <p>${source.preview}...</p>
                </article>
            `
        )
        .join("");
}

function formatErrorMessage(error, fallbackMessage) {
    if (error instanceof TypeError) {
        return "Cannot reach the backend. Make sure uvicorn is running on http://127.0.0.1:8000.";
    }
    return error.message || fallbackMessage;
}
