const API_BASE_URL = "http://127.0.0.1:8000";

const fileInput = document.getElementById("fileInput");
const uploadBtn = document.getElementById("uploadBtn");
const askBtn = document.getElementById("askBtn");
const uploadStatus = document.getElementById("uploadStatus");
const selectedFileElement = document.getElementById("selectedFile");
const activeDocumentElement = document.getElementById("activeDocument");
const uploadHintElement = document.getElementById("uploadHint");
const questionInput = document.getElementById("question");
const chatFeed = document.getElementById("chatFeed");
const modeIndicator = document.getElementById("modeIndicator");

uploadBtn.addEventListener("click", uploadPDF);
askBtn.addEventListener("click", askQuestion);
fileInput.addEventListener("change", updateSelectedFile);

let documentReady = false;
let activeDocumentName = "";
let pendingUpload = false;

function updateSelectedFile() {
    const file = fileInput.files[0];
    if (file) {
        selectedFileElement.textContent = `Selected file: ${file.name}`;
        pendingUpload = true;
        uploadHintElement.textContent = "File selected. Click Upload and Index before asking questions with this PDF.";
    } else {
        selectedFileElement.textContent = "No file selected.";
        pendingUpload = false;
        uploadHintElement.textContent = "Choose a PDF, then click Upload and Index to use it for RAG.";
    }
    updateModeIndicator();
}

async function uploadPDF() {
    const file = fileInput.files[0];

    if (!file) {
        uploadStatus.textContent = "Choose a PDF file first.";
        return;
    }

    const formData = new FormData();
    formData.append("file", file);

    documentReady = false;
    activeDocumentName = "";
    uploadBtn.disabled = true;
    uploadStatus.textContent = "Uploading and indexing your PDF. The first upload can take a little longer while models load.";
    activeDocumentElement.textContent = "Indexing document...";
    uploadHintElement.textContent = "Please wait while the document is being indexed.";
    addAssistantMessage("Uploading and indexing your PDF. Please wait...", [], "system");

    try {
        const response = await fetch(`${API_BASE_URL}/upload`, {
            method: "POST",
            body: formData
        });

        const data = await response.json().catch(() => ({}));
        if (!response.ok) {
            throw new Error(data.detail || "Upload failed.");
        }

        const documentInfo = data.document;
        documentReady = true;
        activeDocumentName = documentInfo.filename;
        pendingUpload = false;
        selectedFileElement.textContent = `Uploaded file: ${file.name}`;
        activeDocumentElement.textContent = `Indexed document: ${documentInfo.filename}`;
        uploadStatus.textContent = `${documentInfo.filename} indexed with ${documentInfo.chunks_created} chunks across ${documentInfo.pages_indexed} pages.`;
        uploadHintElement.textContent = "This indexed PDF will now be used for RAG answers.";
        addAssistantMessage(`Document indexed successfully. I can now answer using RAG from ${documentInfo.filename}.`, [], "system");
    } catch (error) {
        uploadStatus.textContent = formatErrorMessage(error, "Upload failed.");
        activeDocumentElement.textContent = "No document is indexed yet.";
        uploadHintElement.textContent = "Choose a PDF, then click Upload and Index to use it for RAG.";
        addAssistantMessage(formatErrorMessage(error, "Upload failed."), [], "system");
    } finally {
        uploadBtn.disabled = false;
        updateModeIndicator();
    }
}

async function askQuestion() {
    const query = questionInput.value.trim();
    if (!query) {
        addAssistantMessage("Enter a message first.", [], "system");
        return;
    }
    if (pendingUpload) {
        addAssistantMessage("A PDF is selected but not indexed yet. Click Upload and Index first.", [], "system");
        return;
    }

    askBtn.disabled = true;
    addUserMessage(query);
    questionInput.value = "";
    addAssistantMessage(
        documentReady
            ? `Searching ${activeDocumentName} and generating an answer...`
            : "No PDF indexed, so I will answer directly with the LLM.",
        [],
        "system"
    );

    try {
        const response = await fetch(`${API_BASE_URL}/ask`, {
            method: "POST",
            headers: {
                "Content-Type": "application/json"
            },
            body: JSON.stringify({
                query,
                top_k: 3
            })
        });

        const data = await response.json().catch(() => ({}));
        if (!response.ok) {
            throw new Error(data.detail || "Failed to generate an answer.");
        }

        addAssistantMessage(data.answer, data.sources || [], data.mode || "llm");
        if (data.mode === "llm") {
            activeDocumentElement.textContent = "No PDF indexed. Answer generated by the LLM only.";
        } else if (data.document) {
            activeDocumentElement.textContent = `Indexed document: ${data.document}`;
        }
        documentReady = data.mode === "rag";
        if (data.document) {
            activeDocumentName = data.document;
        }
    } catch (error) {
        addAssistantMessage(formatErrorMessage(error, "Failed to generate an answer."), [], "system");
    } finally {
        askBtn.disabled = false;
        updateModeIndicator();
    }
}

function addUserMessage(text) {
    const article = document.createElement("article");
    article.className = "message user-message";
    article.innerHTML = `
        <p class="message-role">You</p>
        <p>${escapeHtml(text)}</p>
    `;
    chatFeed.appendChild(article);
    chatFeed.scrollTop = chatFeed.scrollHeight;
}

function addAssistantMessage(text, sources, mode) {
    const article = document.createElement("article");
    article.className = "message assistant-message";

    const modeLabel = mode === "rag"
        ? "Assistant · RAG"
        : mode === "llm"
            ? "Assistant · LLM"
            : "Assistant · Status";

    let sourcesMarkup = "";
    if (sources.length) {
        const firstSource = sources[0];
        const extraCount = Math.max(sources.length - 1, 0);
        const extraLabel = extraCount > 0 ? ` and ${extraCount} more source${extraCount > 1 ? "s" : ""}` : "";
        sourcesMarkup = `
            <div class="message-sources">
                <p class="source-summary">
                    Source: ${escapeHtml(firstSource.source)} - page ${firstSource.page}${extraLabel}
                </p>
            </div>
        `;
    }

    article.innerHTML = `
        <p class="message-role">${modeLabel}</p>
        <p>${escapeHtml(text)}</p>
        ${sourcesMarkup}
    `;
    chatFeed.appendChild(article);
    chatFeed.scrollTop = chatFeed.scrollHeight;
}

function updateModeIndicator() {
    if (pendingUpload) {
        modeIndicator.textContent = "Current mode: File selected, waiting for indexing";
        return;
    }
    if (documentReady && activeDocumentName) {
        modeIndicator.textContent = `Current mode: RAG with ${activeDocumentName}`;
        return;
    }
    modeIndicator.textContent = "Current mode: LLM only";
}

function formatErrorMessage(error, fallbackMessage) {
    if (error instanceof TypeError) {
        return "Cannot reach the backend. Make sure uvicorn is running on http://127.0.0.1:8000.";
    }
    return error.message || fallbackMessage;
}

function escapeHtml(value) {
    return String(value)
        .replaceAll("&", "&amp;")
        .replaceAll("<", "&lt;")
        .replaceAll(">", "&gt;")
        .replaceAll('"', "&quot;")
        .replaceAll("'", "&#39;");
}
